LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Mixplorer
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Mixplorer.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/priv-app
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := GCamGOPrebuilt PrebuiltGmail Youtube
include $(BUILD_PREBUILT)
